name: newsapp
description: A new Flutter project.

# Prevent accidental publishing
publish_to: 'none' 

# Version info
version: 1.0.0+1

# Environment setup
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.16
  provider: ^6.0.4
  http: ^1.1.1
  share_plus: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Uncomment and add assets if needed
  # assets:
  #   - images/example.png

  # Uncomment and configure custom fonts if needed
  # fonts:
  #   - family: ExampleFont
  #     fonts:
  #       - asset: fonts/ExampleFont-Regular.ttf
